baseURL = 'https://geekifan.github.io/chirpy-starter/'
title = 'Chirpy'
enableGitInfo = false

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true

[pagination]
  pagerSize = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[module]
  [[module.imports]]
    path = "github.com/geekifan/hugo-theme-chirpy"